export const botoxCarousel = {
  id: 'botox-premium',
  title: 'Carrusel Botox Premium',
  subtitle: 'Guía médica de alto impacto · 10 slides · Listo para publicar',
  category: 'medicina-estetica',
  tags: ['botox', 'toxina botulínica', 'medicina estética', 'viral'],
  format: 'portrait',
  palette: {
    bg: '#F7F3EE',
    bg2: '#E8D5BE',
    bg3: '#2A2520',
    accent: '#C4A882',
    text: '#2A2520',
    textLight: '#7A746E',
    white: '#FFFFFF',
    gold: '#C4A882',
  },

  slides: [
    {
      id: 1,
      type: 'cover',
      bgColor: '#F7F3EE',
      layout: 'split-image-left',
      imagePrompt: 'ultra-realistic editorial portrait elegant woman 38 years old, natural flawless glowing skin, champagne beige gradient background, 3/4 angle, serene confident expression, Vogue Beauty editorial quality, cinematic soft lighting from upper left, shallow depth of field, luxury medical aesthetic, Dior skincare campaign, photorealistic 8k, no text',
      imageStyle: 'cinematic',
      imagePosition: 'right',
      elements: {
        label: 'MEDICINA ESTÉTICA PREMIUM',
        headline: ['Todo lo que', 'necesitas saber', 'sobre Botox'],
        subheadline: 'La guía definitiva sobre toxina botulínica',
        cta: 'Desliza para descubrir →',
        handle: '@{handle}',
      },
    },
    {
      id: 2,
      type: 'educational',
      bgColor: '#F7F3EE',
      layout: 'text-right-illustration-left',
      imagePrompt: 'minimal medical anatomy illustration human face profile wireframe elegant golden line art on cream background facial muscles highlighted thin gold lines neurotoxin injection point marked subtle golden circle luxury medical aesthetic no text champagne gold color palette ultra minimal sophisticated editorial',
      imageStyle: 'illustration',
      elements: {
        label: '01 / FUNDAMENTOS',
        headline: ['¿Qué es', 'realmente?'],
        accent: 'Toxina Botulínica Tipo A',
        body: 'La toxina botulínica es una proteína neuromoduladora purificada que bloquea temporalmente la señal nerviosa hacia músculos faciales específicos.\n\nAl relajar estos músculos, las arrugas dinámicas se suavizan de forma progresiva y completamente natural.',
        bullets: [
          'Acción selectiva sobre músculos específicos',
          'Sin afectar la sensibilidad de la piel',
          'Proteína purificada — efecto reversible',
          'Aprobado por FDA · +20 años de evidencia clínica',
        ],
      },
    },
    {
      id: 3,
      type: 'face-map',
      bgColor: '#F7F3EE',
      layout: 'face-map-center',
      imagePrompt: 'ultra-realistic frontal female face portrait black and white editorial flawless skin neutral expression symmetrical composition soft studio lighting anatomical precision medical aesthetic photography no jewelry hair pulled back Vogue Beauty black and white ultra sharp facial features for medical face mapping overlay',
      imageStyle: 'photorealistic',
      elements: {
        label: '02 / ÁREAS DE TRATAMIENTO',
        headline: ['¿Dónde', 'se aplica?'],
        accent: '6 zonas principales',
        zones: [
          { num: '01', name: 'FRENTE', desc: 'Líneas horizontales' },
          { num: '02', name: 'ENTRECEJO', desc: 'Arrugas del ceño' },
          { num: '03', name: 'PATAS DE GALLO', desc: 'Líneas perioculares' },
          { num: '04', name: 'LABIOS', desc: 'Código de barras' },
          { num: '05', name: 'MENTÓN', desc: 'Piel de naranja' },
          { num: '06', name: 'CUELLO', desc: 'Nefertiti lift' },
        ],
        note: '+ Bruxismo · Sonrisa gingival · Sudoración · Migraña',
      },
    },
    {
      id: 4,
      type: 'benefits',
      bgColor: '#F7F3EE',
      layout: 'grid-benefits',
      imagePrompt: 'close-up portrait 32-year-old woman natural radiant glowing skin completely relaxed natural expression warm golden light champagne background luxury beauty editorial no heavy makeup visible skin texture and luminosity Augustinus Bader skincare campaign aesthetic rested refreshed appearance ultra premium photorealistic',
      imageStyle: 'instagram',
      elements: {
        label: '03 / RESULTADOS',
        headline: ['Lo que', 'realmente', 'logra'],
        accent: 'Beneficios documentados clínicamente',
        benefits: [
          { icon: '◇', title: 'Prevención', desc: 'Detiene el progreso de líneas activas' },
          { icon: '◇', title: 'Descansada', desc: 'Elimina signos de cansancio y tensión' },
          { icon: '◇', title: '100% Natural', desc: 'Sin alterar tu identidad facial' },
          { icon: '◇', title: 'Sin cirugía', desc: 'Sin cicatrices ni recuperación' },
          { icon: '◇', title: '15 minutos', desc: 'Regresa a tus actividades hoy' },
          { icon: '◇', title: 'Gradual', desc: 'Resultados naturales del día 3 al 14' },
        ],
        quote: '"El mejor Botox es el que nadie nota."',
      },
    },
    {
      id: 5,
      type: 'myths',
      bgColor: '#2A2520',
      layout: 'dark-myths',
      imagePrompt: 'luxury dark editorial background deep warm black texture subtle grain overlay premium medical aesthetic dark atmosphere champagne and gold accents sophisticated moody no people for text overlay abstract',
      imageStyle: 'cinematic',
      isDark: true,
      elements: {
        label: '04 / DESMITIFICANDO',
        headline: ['Mitos que', 'frenan tu', 'decisión'],
        accent: 'La verdad basada en evidencia',
        myths: [
          {
            myth: '"Deja la cara completamente congelada"',
            truth: 'La técnica moderna preserva el 100% de tus expresiones. Solo relaja la contracción excesiva.',
          },
          {
            myth: '"Solo es para personas mayores"',
            truth: 'El botox preventivo desde los 25 años es la estrategia más inteligente contra el envejecimiento.',
          },
          {
            myth: '"Es peligroso y tóxico"',
            truth: 'Más de 20 años de uso aprobado por FDA con perfil de seguridad excepcional.',
          },
          {
            myth: '"Duele mucho"',
            truth: 'Agujas ultrafinas 30-33G. La mayoría describe solo presión leve durante segundos.',
          },
        ],
      },
    },
    {
      id: 6,
      type: 'timeline',
      bgColor: '#F7F3EE',
      layout: 'timeline-vertical',
      imagePrompt: 'minimal abstract golden timeline design element on cream background elegant dots and lines luxury medical aesthetic no faces no text champagne and gold gradient subtle bokeh premium minimalist',
      imageStyle: 'illustration',
      elements: {
        label: '05 / EVOLUCIÓN',
        headline: ['¿Cuándo verás', 'los resultados?'],
        accent: 'Cronología exacta post-tratamiento',
        timeline: [
          { day: 'DÍA 1', title: 'Aplicación completada', desc: 'Leve enrojecimiento que desaparece en horas. Actividad normal inmediata.' },
          { day: 'DÍA 3–4', title: 'Primeras señales', desc: 'El músculo comienza a relajarse gradualmente. Primero notarás el efecto.' },
          { day: 'DÍA 7', title: 'Efecto visible', desc: 'Arrugas suavizadas. Expresión más relajada y descansada.' },
          { day: 'DÍA 14', title: 'Resultado óptimo', desc: 'Tu mejor versión. El seguimiento garantiza perfección personalizada.' },
        ],
      },
    },
    {
      id: 7,
      type: 'maintenance',
      bgColor: '#E8D5BE',
      layout: 'stat-hero',
      imagePrompt: 'abstract luxury time concept calendar minimal golden circles dots on champagne background elegant premium medical aesthetic no text no faces soft golden light bokeh minimalist',
      imageStyle: 'artistic',
      elements: {
        label: '06 / MANTENIMIENTO',
        headline: ['¿Cuánto', 'tiempo dura?'],
        statNumber: '4–6',
        statLabel: 'meses de duración',
        accent: 'Y cómo maximizar cada sesión',
        factors: [
          { name: 'METABOLISMO', desc: 'Más activo = absorción más rápida' },
          { name: 'ACTIVIDAD', desc: 'Ejercicio intenso puede acortar el efecto' },
          { name: 'TÉCNICA', desc: 'Dosis y profundidad son determinantes' },
          { name: 'CONSTANCIA', desc: 'Los músculos desarrollan memoria de relajación' },
        ],
        insight: 'Con tratamientos regulares, el efecto se prolonga naturalmente con cada sesión.',
      },
    },
    {
      id: 8,
      type: 'preventive',
      bgColor: '#F7F3EE',
      layout: 'editorial-full',
      imagePrompt: 'editorial beauty portrait young woman 26-28 years absolutely natural flawless glowing skin no makeup appearance soft champagne studio background 3/4 angle natural window light visible perfect skin texture with subtle luminosity luxury skincare campaign Augustinus Bader aesthetic young fresh premium photorealistic',
      imageStyle: 'instagram',
      elements: {
        label: '07 / MEDICINA PREVENTIVA',
        headline: ['El secreto de', 'quienes envejecen', 'mejor'],
        accent: 'Botox preventivo desde los 25 años',
        body: 'Las arrugas dinámicas se forman por miles de contracciones repetidas durante años.\n\nEl botox preventivo interrumpe ese ciclo antes de que las líneas se vuelvan permanentes.',
        quote: '"No es vanidad.\nEs inversión en tu piel del futuro."',
        ranges: [
          { age: '25–30 años', action: 'Prevención de líneas nacientes' },
          { age: '30–38 años', action: 'Corrección y mantenimiento' },
          { age: '38+ años', action: 'Rejuvenecimiento natural continuo' },
        ],
      },
    },
    {
      id: 9,
      type: 'trust',
      bgColor: '#F7F3EE',
      layout: 'trust-pillars',
      imagePrompt: 'luxury medical aesthetic clinic interior elegant doctor gloved hands preparing botox injection ultra premium minimalist clinic background blurred warm soft studio lighting medical precision Dior Beauty campaign champagne and white color palette selective focus on hands and syringe depth of field no face visible premium medical atmosphere',
      imageStyle: 'cinematic',
      elements: {
        label: '08 / ESTÁNDARES MÉDICOS',
        headline: ['Tu seguridad', 'es la única', 'prioridad'],
        accent: 'Protocolo médico de máximo nivel',
        pillars: [
          { title: 'EVALUACIÓN\nPERSONALIZADA', desc: 'Historia clínica completa y análisis de contraindicaciones' },
          { title: 'DIAGNÓSTICO\nFACIAL', desc: 'Análisis de anatomía única y simetría personalizada' },
          { title: 'TÉCNICA\nCERTIFICADA', desc: 'Formación internacional y experiencia documentada' },
          { title: 'SEGUIMIENTO\nGARANTIZADO', desc: 'Control post-tratamiento incluido en cada sesión' },
        ],
        credentials: [
          'Médico especializado en medicina estética',
          'Toxina botulínica certificada (Allergan / Ipsen)',
          'Instalaciones con estándares internacionales',
        ],
        quote: '"La diferencia entre un resultado natural y uno artificial es la mano del médico."',
        doctor: '{doctor}',
      },
    },
    {
      id: 10,
      type: 'cta',
      bgColor: '#F7F3EE',
      layout: 'cta-full',
      imagePrompt: 'ultra-close-up female eye perfect skin no wrinkles golden hour light single drop serum on cheekbone champagne background extreme detail macro lens medical aesthetic luxury Vogue Beauty cover quality photorealistic editorial',
      imageStyle: 'cinematic',
      elements: {
        label: 'TU PRÓXIMO PASO',
        headline: ['Tu mejor versión', 'puede verse', 'completamente', 'natural.'],
        subheadline: 'AGENDA TU VALORACIÓN PERSONALIZADA',
        body: 'Evaluación médica · Sin compromiso · 100% personalizada',
        ctaInstagram: '@{handle}',
        ctaWhatsapp: '{whatsapp}',
        trust: 'Cupos limitados por agenda · Reserva tu espacio hoy',
        doctor: '{doctor}',
        specialty: 'Especialista en Medicina Estética',
      },
    },
  ],
}

import { gammaCarousel } from './gammaCarousel'

export const TEMPLATES = [
  {
    id: 'gamma-botox-premium',
    title: '✦ Gamma · Arte de la Juventud',
    subtitle: 'Generado con Gamma AI · Flux images · Ultra premium',
    category: 'Medicina Estética',
    slides: 10,
    color: '#C4AA80',
    emoji: '◈',
    data: gammaCarousel,
    tags: ['gamma', 'flux', 'premium', 'botox'],
    badge: 'GAMMA AI',
  },
  {
    id: 'botox-premium',
    title: 'Botox Premium',
    subtitle: '10 slides · Guía completa · Alta conversión',
    category: 'Medicina Estética',
    slides: 10,
    color: '#C4A882',
    emoji: '✦',
    data: botoxCarousel,
    tags: ['viral', 'educativo', 'conversión'],
  },
  {
    id: 'coming-soon-1',
    title: 'Rellenos & Filler',
    subtitle: 'Próximamente',
    category: 'Medicina Estética',
    slides: 10,
    color: '#B09080',
    emoji: '◈',
    comingSoon: true,
  },
  {
    id: 'coming-soon-2',
    title: 'Skincare Routine',
    subtitle: 'Próximamente',
    category: 'Belleza',
    slides: 8,
    color: '#8C9E8C',
    emoji: '◉',
    comingSoon: true,
  },
  {
    id: 'coming-soon-3',
    title: 'Hidratación Facial',
    subtitle: 'Próximamente',
    category: 'Medicina Estética',
    slides: 8,
    color: '#8C9EA8',
    emoji: '◌',
    comingSoon: true,
  },
]
