// ── Carrusel generado con Gamma AI + Flux model ────────────────────────────
// Imágenes reales generadas por Gamma con flux-2-klein photorealistic
// Contenido médico premium revisado

export const gammaCarousel = {
  id: 'gamma-botox-premium',
  title: 'Gamma · El Arte de la Juventud',
  subtitle: 'Generado con Gamma AI · Imágenes premium Flux · 10 slides',
  category: 'medicina-estetica',
  tags: ['gamma', 'flux', 'premium', 'botox'],
  format: 'portrait',
  palette: {
    bg: '#F7F3EE', bg2: '#E8D5BE', accent: '#C4A882', text: '#2A2520', dark: '#0C2530',
  },
  slides: [
    {
      id: 1, type: 'cover', bgColor: '#0C2530', isDark: true, layout: 'split-image-left',
      imagePrompt: 'elegant woman profile close-up soft lighting golden champagne tones editorial beauty luxury medical aesthetics',
      imageStyle: 'luxury',
      gammaImage: 'https://cdn.gamma.app/dfrbaujzzy6crzk/generated-images/bXFZSTZTBIcPIgIEoZe7V.png',
      elements: {
        label: 'MEDICINA ESTÉTICA PREMIUM',
        headline: ['El Arte de', 'la Juventud'],
        accent: 'Toxina Botulínica · Medicina Estética de Precisión',
        body: null, bullets: null, quote: null,
        cta: 'Desliza para descubrir →',
        handle: '{handle}',
      },
    },
    {
      id: 2, type: 'educational', bgColor: '#F7F3EE', isDark: false, layout: 'text-right-illustration-left',
      imagePrompt: 'elegant illustration facial anatomy muscle diagram champagne gold teal tones artistic medical editorial',
      imageStyle: 'illustration',
      gammaImage: 'https://cdn.gamma.app/dfrbaujzzy6crzk/generated-images/uIBJD_DyPo4vjr7mymM7z.png',
      elements: {
        label: '01 / FUNDAMENTOS CIENTÍFICOS',
        headline: ['¿Qué es la', 'Toxina', 'Botulínica?'],
        accent: 'Fundamentos Científicos',
        body: 'La toxina botulínica es una proteína purificada de origen biológico que actúa sobre las terminaciones nerviosas, bloqueando temporalmente las señales musculares responsables de la contracción.\n\nEl resultado: músculos faciales en reposo, piel más suave y una apariencia naturalmente rejuvenecida. Sin cirugía, sin tiempo de recuperación prolongado.',
        bullets: null,
        quote: null,
        note: 'Aprobado por la FDA y avalado por décadas de investigación clínica en estética médica.',
      },
    },
    {
      id: 3, type: 'face-map', bgColor: '#F7F3EE', isDark: false, layout: 'face-map-center',
      imagePrompt: 'frontal female face portrait neutral expression symmetrical medical aesthetics face mapping editorial',
      imageStyle: 'photorealistic',
      gammaImage: null,
      elements: {
        label: '02 / ÁREAS DE TRATAMIENTO',
        headline: ['Face Mapping:', 'Zonas de', 'Aplicación'],
        accent: 'Cada zona facial responde con precisión al tratamiento personalizado.',
        zones: [
          { num: '①', name: 'Frente', desc: 'Líneas horizontales de expresión' },
          { num: '②', name: 'Entrecejo', desc: 'Líneas del "11" y ceño fruncido' },
          { num: '③', name: 'Patas de Gallo', desc: 'Arrugas perioculares laterales' },
          { num: '④', name: 'Nariz', desc: 'Líneas bunny lines y punta nasal' },
          { num: '⑤', name: 'Labios', desc: 'Código de barras y volumen sutil' },
          { num: '⑥', name: 'Mentón y Cuello', desc: 'Bandas platismales y mentón' },
        ],
        body: null, bullets: null, quote: null,
      },
    },
    {
      id: 4, type: 'benefits', bgColor: '#F7F3EE', isDark: false, layout: 'grid-benefits',
      imagePrompt: 'close-up portrait woman glowing skin natural beauty champagne background luxury editorial lifestyle',
      imageStyle: 'luxury',
      gammaImage: null,
      elements: {
        label: '03 / BENEFICIOS REALES',
        headline: ['6 Beneficios', 'Reales del', 'Botox'],
        accent: 'Documentados clínicamente',
        benefits: [
          { icon: '✦', title: 'Suaviza arrugas de expresión', desc: 'Resultados visibles desde el día 3, con máximo efecto a los 14 días.' },
          { icon: '✦', title: 'Efecto preventivo', desc: 'Frena la formación de arrugas permanentes antes de que aparezcan.' },
          { icon: '✦', title: 'Sin tiempo de recuperación', desc: 'Procedimiento de 15–30 minutos. Retoma tu rutina inmediatamente.' },
          { icon: '✦', title: 'Lifting no quirúrgico', desc: 'Reposiciona cejas y eleva la mirada con técnica de precisión.' },
          { icon: '✦', title: 'Hiperhidrosis y bruxismo', desc: 'Trata el sudor excesivo y el apretamiento mandibular con eficacia clínica.' },
          { icon: '✦', title: 'Resultados naturales', desc: 'Con técnica experta, conservas expresividad y luce siempre tú misma.' },
        ],
        body: null, bullets: null, quote: null,
      },
    },
    {
      id: 5, type: 'myths', bgColor: '#0C2530', isDark: true, layout: 'dark-myths',
      imagePrompt: 'elegant confident woman calm expression luxury medical aesthetics champagne background editorial portrait',
      imageStyle: 'luxury',
      gammaImage: 'https://cdn.gamma.app/dfrbaujzzy6crzk/generated-images/Fk8QVRDIKuIdkVRb3VIjZ.png',
      elements: {
        label: '04 / DESMITIFICANDO',
        headline: ['Mitos vs.', 'Realidad'],
        accent: 'La verdad basada en evidencia médica',
        myths: [
          { myth: '"Te deja cara de muñeca"', truth: 'La técnica médica preserva el movimiento natural. La sobre-aplicación es errónea, no el tratamiento.' },
          { myth: '"Es peligroso"', truth: 'Con dosis terapéuticas certificadas y médico especializado, el perfil de seguridad es excelente.' },
          { myth: '"Crea adicción"', truth: 'No genera dependencia física. Puedes suspenderlo y los músculos recuperan su actividad normal.' },
          { myth: '"Solo es para mayores de 40"', truth: 'El botox preventivo desde los 25 años es una estrategia validada por dermatología moderna.' },
        ],
        body: null, bullets: null, quote: null,
      },
    },
    {
      id: 6, type: 'timeline', bgColor: '#F7F3EE', isDark: false, layout: 'timeline-vertical',
      imagePrompt: 'minimal abstract golden timeline dots lines champagne background luxury medical aesthetic no faces',
      imageStyle: 'illustration',
      gammaImage: null,
      elements: {
        label: '05 / EVOLUCIÓN',
        headline: ['Timeline de', 'Resultados'],
        accent: 'Tu piel evoluciona con precisión en cada etapa',
        timeline: [
          { day: 'Día 1', title: 'Aplicación completada', desc: 'Leve enrojecimiento puntual. Sin dolor relevante. Retoma actividades al instante.' },
          { day: 'Día 3', title: 'Primeros resultados', desc: 'Primeros resultados visibles. La musculatura comienza a relajarse gradualmente.' },
          { day: 'Día 7', title: 'Efecto en desarrollo', desc: 'Las arrugas dinámicas se suavizan notablemente.' },
          { day: 'Día 14', title: 'Resultado óptimo', desc: 'Máxima suavidad, expresión natural y luminosidad completa.' },
        ],
        note: 'El resultado completo se aprecia entre los 10 y 14 días postratamiento.',
        body: null, bullets: null, quote: null,
      },
    },
    {
      id: 7, type: 'stat', bgColor: '#E8D5BE', isDark: false, layout: 'stat-hero',
      imagePrompt: 'abstract luxury calendar time concept golden circles minimal champagne background premium',
      imageStyle: 'illustration',
      gammaImage: null,
      elements: {
        label: '06 / DURACIÓN',
        headline: ['4 a 6 Meses', 'de Resultados'],
        statNumber: '4–6',
        statLabel: 'meses de duración promedio',
        accent: 'Resultados que duran',
        body: 'La duración varía según el metabolismo individual, la zona tratada y la dosis aplicada. La mayoría de los pacientes mantienen resultados óptimos entre 4 y 6 meses.\n\nCon sesiones periódicas, el músculo se re-educa y los resultados tienden a prolongarse con el tiempo.',
        bullets: null, quote: null,
        factors: [
          { name: '95%', desc: 'Satisfacción de pacientes tratados' },
          { name: '3–4×', desc: 'Sesiones por año para mantenimiento' },
        ],
      },
    },
    {
      id: 8, type: 'preventive', bgColor: '#F7F3EE', isDark: false, layout: 'editorial-full',
      imagePrompt: 'young elegant woman glowing skin confident smile warm lighting natural beauty editorial portrait luxury skincare',
      imageStyle: 'luxury',
      gammaImage: 'https://cdn.gamma.app/dfrbaujzzy6crzk/generated-images/bGlQaB_5FwqCXrIP-78X2.png',
      elements: {
        label: '07 / MEDICINA PREVENTIVA',
        headline: ['Botox Preventivo:', 'Empieza a', 'los 25'],
        accent: 'Prevenir es más efectivo que corregir',
        body: 'La medicina estética moderna ha redefinido el concepto de tratamiento. Cuando iniciamos el botox preventivo en etapas tempranas, evitamos que las líneas dinámicas se conviertan en arrugas estáticas permanentes.',
        quote: 'Prevenir es más efectivo que corregir.',
        ranges: [
          { age: '25–30 años', action: 'Microzonas de expresión. Dosis mínimas de precisión.' },
          { age: '30–40 años', action: 'Mantenimiento activo. Protocolo personalizado consolidado.' },
          { age: '40+ años', action: 'Corrección + prevención. Resultados más naturales y duraderos.' },
        ],
        bullets: null,
      },
    },
    {
      id: 9, type: 'trust', bgColor: '#F7F3EE', isDark: false, layout: 'trust-pillars',
      imagePrompt: 'luxury medical professional gloved hands precision injection elegant clinic premium atmosphere',
      imageStyle: 'cinematic',
      gammaImage: 'https://cdn.gamma.app/dfrbaujzzy6crzk/generated-images/Mv7hIxuv4epGnuh39Geh5.png',
      elements: {
        label: '08 / ESTÁNDARES MÉDICOS',
        headline: ['Tu Seguridad', 'es Nuestra', 'Prioridad'],
        accent: 'Protocolo médico de máximo nivel',
        body: null,
        pillars: [
          { title: 'CERTIFICACIÓN\nINTERNACIONAL', desc: 'Formación avalada por sociedades médicas reconocidas globalmente.' },
          { title: 'TOXINA 100%\nORIGINAL', desc: 'Uso exclusivo de marcas farmacéuticas certificadas y trazables.' },
          { title: 'PROTOCOLO DE\nSEGURIDAD', desc: 'Evaluación médica previa, consentimiento informado y seguimiento.' },
        ],
        credentials: [
          'Especialista certificado en medicina estética',
          'Toxina botulínica certificada (Allergan / Ipsen)',
          'Instalaciones con estándares internacionales',
        ],
        quote: '"La diferencia entre un resultado natural y uno artificial es la mano del médico."',
        doctor: '{doctor}',
        bullets: null,
      },
    },
    {
      id: 10, type: 'cta', bgColor: '#0C2530', isDark: true, layout: 'cta-full',
      imagePrompt: 'elegant woman luxury spa reception golden champagne teal ambiance premium medical clinic invitation',
      imageStyle: 'luxury',
      gammaImage: 'https://cdn.gamma.app/dfrbaujzzy6crzk/generated-images/JO5CFu8IiRXHMSwhugHjE.png',
      elements: {
        label: 'TU PRÓXIMO PASO',
        headline: ['Tu Consulta', 'Premium', 'Te Espera'],
        subheadline: 'DA EL PRIMER PASO HOY',
        accent: 'Agenda tu valoración personalizada — sin compromiso',
        body: null,
        bullets: [
          '✦ Evaluación Facial Completa — diagnóstico sin compromiso',
          '✦ Plan a Tu Medida — protocolo para tus objetivos',
          '✦ Resultados Garantizados — seguimiento incluido',
        ],
        quote: 'Agenda tu consulta hoy · @drcolmenarez\nMedicina Estética de Lujo · Resultados que Hablan por Sí Solos',
        ctaInstagram: '{handle}',
        ctaWhatsapp: '{whatsapp}',
        trust: 'Cupos limitados · Reserva tu espacio hoy',
        doctor: '{doctor}',
      },
    },
  ],
}
